name: Process IPs and Commit JP Results

on:
  workflow_dispatch:
  schedule:
    - cron: '00 00 * * *'

jobs:
  process-ips:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # 提交权限
      actions: read
      id-token: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Download the ZIP file
      - name: Download ZIP file
        run: wget -O ips.zip https://zip.baipiao.eu.org

      # Step 3: Unzip the file
      - name: Unzip the downloaded file
        run: unzip ips.zip -d extracted

      # Step 4: Merge all TXT files into one
      - name: Merge TXT files
        run: cat extracted/*.txt > merged_ips.txt

      # Step 5: Filter JP IPs
      - name: Filter JP IPs
        run: |
          # 检查 merged_ips.txt 文件是否存在
          if [ ! -f "merged_ips.txt" ]; then
            echo "Error: merged_ips.txt not found!"
            exit 1
          fi

          # 创建 jp_ips.txt 文件
          touch jp_ips.txt

          while read -r ip; do
            # 调用 API 获取地理位置
            geo=$(curl -s -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" "https://api.ip.sb/geoip/$ip" | jq -r '.country_code' || echo "ERROR")
            
            # 如果是日本 IP，保存到 jp_ips.txt 文件，否则输出到控制台
            if [ "$geo" == "JP" ]; then
              echo "$ip" >> jp_ips.txt
              echo "$ip $geo"
            elif [ "$geo" == "ERROR" ]; then
              echo "$ip API Error"
            else
              echo "$ip $geo"
            fi

            # 延迟等待 1 秒
            sleep 1
          done < merged_ips.txt
      # Step 7: Commit and push results
      - name: Commit and push results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add jp_ips.txt
          git commit -m "Add valid JP IPs with latency results"
          git push
