name: 删除
on:
  workflow_dispatch:
permissions:
  contents: write
  discussions: write
jobs:
  process-ips:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: bulid
        run: |
          export CLOUDFLARE_API_KEY="${{ secrets.CLOUDFLARE_API_KEY }}"
          export CLOUDFLARE_EMAIL="${{ vars.CLOUDFLARE_EMAIL }}"
          export DOMAIN_NAME="${{ vars.DOMAIN_NAME }}"
          bash d.sh
