name: Filter JP IPs with Open 443 Port

on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  filter-jp-ips:
    name: Filter and Check IPs
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 Ubuntu 环境
    permissions:
      contents: write  # 提交权限
      actions: read
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # 拉取代码仓库

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq netcat-openbsd

      - name: Filter JP IPs and Check Multiple Ports
        run: |
          # 清空输出文件
          > open_ips.txt

          # 定义需要检测的端口列表
          ports=("443" "2053" "2083" "2087" "2096" "8443")

          # 遍历 IP 文件
          while read -r ip; do
            # 获取地理位置数据 (country 和 country_code)
            geo=$(curl -s -H "User-Agent: Mozilla/5.0" "https://api.ip.sb/geoip/$ip")
            country=$(echo "$geo" | jq -r '.country // "Unknown"')
            country_code=$(echo "$geo" | jq -r '.country_code // "Unknown"')

            # 检查是否是日本的 IP
            if [[ "$country_code" == "JP" ]]; then
              # 仅提取 IP 地址
              clean_ip=$(echo "$ip" | awk -F'#' '{print $1}')

              # 循环检查端口
              for port in "${ports[@]}"; do
                if nc -z -w2 "$clean_ip" "$port"; then
                  # 如果端口通，写入文件
                  echo "$ip:$port#$country" | tee -a open_ips.txt
                fi
              done
            fi
            sleep 1  # 避免 API 请求过快
          done < jp_ips.txt

      - name: Commit and Push Results
        run: |
          date > generated.txt
          # Note: the following account information will not work on GHES
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # 添加和提交更改
          git add open_ips.txt
          git commit -m "Add filtered JP IPs with open"

          # 推送到仓库
          git push
