name: 脚本混淆
on:
  workflow_dispatch:
  schedule:
    - cron: '00 00 * * *'

jobs:
  process-ips:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # 提交权限
      actions: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: 安装依赖
        run: |
          sudo apt-get update && sudo apt-get install python3 python3-pip python3-argcomplete xclip git
      - name: 安装Bashfuscator
        run: |
          git clone https://github.com/Bashfuscator/Bashfuscator
          cd Bashfuscator
          python3 setup.py install --user
      - run: |
          bashfuscator -c "cat api.sh"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add api.sh
          git commit -m "Add valid JP IPs with latency results"
          git push
