name: jpip
on:
  workflow_dispatch:
permissions:
  contents: write
  discussions: write
jobs:
  process-ips:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: bulid
        run: |
          bash d.sh
          bash api.sh
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *_ips.txt
          git commit -m "Add valid JP IPs with latency results"
          git push
