name: jpip
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
  discussions: write
jobs:
  process-ips:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: |
          bash d.sh
          bash api.sh
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *_ips.txt
          git commit -m "Add valid JP IPs with latency results"
          git push
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          repository: my_gh_org/my_gh_repo
          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: "*_ips.txt"
