name: jpip
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
  discussions: write
jobs:
  process-ips:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: "*_ips.txt"
